name: Deploy to AWS

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  deploy:
    name: Terraform apply on AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: hashicorp/setup-terraform@v1
    - run: terraform init \
      -backend-config="token=${{ secrets.HASHICORP_TOKEN }}" \
      -backend-config="organization=${{ secrets.HASHICORP_ORGANIZATION }}"

    - id: plan
      run: terraform plan -no-color

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve 